### ISSUE TITLE
Incorrect React Version in play.

### ISSUE THREAD

**Issue by DevJonTaylor** [DevJonTaylor/code-vegeta#7]
@stripe/react-stripe-js - v1.8.1
@stripe/stripe-js - v1.29.0
daisyui - v2.15.0
dotenv - v16.0.1
grapesjs - v0.18.4

react - v17.0.2
react-dom - v17.0.2

react-scripts - v5.0.1
strip - v^9.4.

**Comment by laszlo-ratesic** [comment]
React version successfully upgraded, closing issue now.
